name: LoreLocks
main: com.github.derwisch.loreLocks.LoreLocks
version: ${project.version}

permissions:
    lorelocks.bypass:
        description: Allows to bypass chest locks
        default: false
    lorelocks.pick.*:
        description: Allows to pick all locks
        default: false
        children:
            - lorelocks.pick.1 
            - lorelocks.pick.2 
            - lorelocks.pick.3 
            - lorelocks.pick.4 
            - lorelocks.pick.5
    lorelocks.pick.1:
        description: Allows to pick level 1 locks
        default: false
    lorelocks.pick.2:
        description: Allows to pick level 2 locks
        default: false
    lorelocks.pick.3:
        description: Allows to pick level 3 locks
        default: false
    lorelocks.pick.4:
        description: Allows to pick level 4 locks
        default: false
    lorelocks.pick.5:
        description: Allows to pick level 5 locks
        default: false
